name: Web CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  e2e-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install API dependencies
        run: pip install -r api/requirements.txt

      - name: Run API Migrations
        run: |
          cp api/.env.example api/.env
          export PYTHONPATH=$PYTHONPATH:./api
          alembic -c api/alembic.ini upgrade head

      - name: Start API server
        run: uvicorn app.main:app --port 8000 --app-dir api &

      - name: Install web dependencies
        run: npm install
        working-directory: ./web

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./web

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./web
